sonar.projectKey=Revanth1486_weather-dashboard-devops
sonar.organization=revanth1486
sonar.projectName=Weather Dashboard DevOps
sonar.projectVersion=1.0
sonar.sources=backend/src,frontend/src
sonar.tests=backend/tests
sonar.javascript.lcov.reportPaths=backend/coverage/lcov.info
sonar.exclusions=**/node_modules/**,**/coverage/**
sonar.sourceEncoding=UTF-8